{% set name = "pyaaf2" %}
{% set version = "1.7.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: e18e5a84bca4ea18c1b9e8384958e2f6d296195c901a448f71f830b22b89c225

build:
  noarch: python
  number: 1
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
  run:
    - python >={{ python_min }}

test:
  requires:
    - python {{ python_min }}
  imports:
    - aaf2
    - aaf2.model
    - aaf2.model.ext

about:
  home: https://github.com/markreidvfx/pyaaf2
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: A python module for reading and writing advanced authoring format files
  doc_url: https://pyaaf.readthedocs.io/en/latest

extra:
  recipe-maintainers:
    - vvzen
